# WILDCARDS
all: '.+'
all_except_ws: '[^ ]+'

# IP ADDRESSES
ipv4_address: '(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'

# BASIC DATA TYPES
alphabetic_disallow_ws: '[a-zA-Z]+'
alphabetic_allow_ws: '[a-zA-Z\s]+'
alphanumeric_disallow_ws: '[0-9a-zA-Z]+'
alphanumeric_allow_ws: '[0-9a-zA-Z\s]+'
alphanumeric_underscored: '[0-9a-zA-Z_]+'
integer: '[0-9]+'
float: '[0-9]+\.[0-9]+'

uuid: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'