general:
  - '^\s{0,}$' # Empty
  - '^\s{0,}{#.+#}$' # Jinja2 comment line
  - '^\s{0,}\!.{0,}\n{0,1}' # Config comment line

# Add items that are specific to your template below with template name as header.
# For example, dsl_golden_config.j2 should have the header dsl_golden_config.

audit:
  - '\s{0,}href: [0-9a-zA-Z]+'
  - '\s{0,}id: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  - '\s{0,}comment: [0-9a-zA-Z]+'
  - '\s{0,}hitCounts: [0-9a-zA-Z]+'
  - '\s{0,}link: null$'